# image: node:8.9.0

# before_script:
#   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#   - npm install


# stages:
#   - deploy

# deployToAWS:
#   only:
#     - prod
#   stage: deploy
#   script:
#     - npm run build
#     - bash deploy/deploy.sh